name: Run tests on MacOS

on:
  push:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Blah
        run: |
        RUST_VERSION="$(cat rust-toolchain.toml | grep '^channel\s*=' | cut --delimiter '=' --fields=2 | sed 's/"//g' | sed 's/^[ \t]*//')"
        echo "rust-version=${RUST_VERSION}" >> "$GITHUB_OUTPUT"
